name: ci-build

on:
  push:


jobs:
  # Main build, creates firmware update image
  build-soc:
    runs-on: ubuntu-latest
    steps:
    # Checkout Repository
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: false # Note: not Recursive (we only need recursive on picolibc)

    - name: Checkout Submodule
      run: |
        git submodule update --init
        git submodule update --init --recursive -- gateware/deps/pythondata-software-picolibc

    - name: YosysHQ setup
      uses: YosysHQ/setup-oss-cad-suite@v1
      
    - name: RISC-V GNU setup
      uses: gregdavill/setup-riscv-gnu-toolchain@v1.0
    
    - name: configure python
      run: |
        python3 -m pip install setuptools
        python3 -m pip install pycrc
        python3 -m pip install wheel
        python3 -m pip install construct
        python3 -m pip install Sphinx sphinxcontrib-wavedrom meson ninja setuptools_scm Jinja2
        
    - name: Patch
      working-directory: ./gateware/deps
      run: git apply --verbose --directory=gateware/deps/litex 001-litex-jtagg-support.diff

    - name: Litex build
      working-directory: ./gateware
      run: |
        python3 butterstick-bitstream.py
